import "./globals.css";

export const metadata = {
  title: 'Loopple Next.js App',
  description: 'Generated by Loopple',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
